frontend:
  themes: !include_dir_merge_named themes

automation:
camera:
climate:
config:
conversation:
device_tracker:
diagnostics:
hardware:
input_button:
logbook:
media_source:
mobile_app:
my:
person:
# script: 
ssdp:
sun:
system_health:
system_log:
tts:
  - platform: google_translate
zeroconf:

