# Snippet to be inserted in configuration.yaml
# Load frontend themes from the themes folder
frontend:
  themes:
    My Theme: # Define new theme for which we change the colors
      # This theme must be selected in the user preference to become active
      # Allow switch between dark and light mode and inherit styles from these
      primary-color: coral
      modes:
        light:
          secondary-text-color: olive
        dark:
          secondary-text-color: slategray
      # redefine energy source colors
      energy-grid-consumption-color-0: "#587cfc"
      energy-grid-consumption-color-1: "#0000ff"
      energy-grid-consumption-color-2: "#b5b5b5"
      energy-grid-consumption-color-3: "#ebebeb"
      energy-grid-consumption-color-4: "#fa7575"
      energy-grid-consumption-color-5: "#ff0000"

energy:

homeassistant:
  customize:
    sensor.bedroom_1_lights_power:
      device_class: power
    sensor.bedroom_2_lights_power:
      device_class: power
    sensor.bedroom_3_lights_power:
      device_class: power
    sensor.living_room_lights_power:
      device_class: power
    sensor.front_door_lights_power:
      device_class: power
    # sensor.bedroom_1_lights_energy:
    #   state_class: total_increasing
    #   device_class: energy
    # sensor.bedroom_2_lights_energy:
    #   state_class: total_increasing
    #   device_class: energy
    # sensor.bedroom_3_lights_energy:
    #   state_class: total_increasing
    #   device_class: energy
    # sensor.living_room_lights_energy:
    #   state_class: total_increasing
    #   device_class: energy
    # sensor.front_door_lights_energy:
    #   state_class: total_increasing
    #   device_class: energy
      
# input_number:
#   tc_oil_price:
#     name: TC Oil Price
#     icon: mdi:cash
#     min: 0
#     max: 100
#     step: .001
#     mode: box
#     unit_of_measurement: GBP/l

template:
  - trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: time_pattern
      minutes: '0'
      seconds: '15'
    - platform: state
    #   entity_id: sensor.tc_oil_usage
      entity_id: sensor.sfups_power
    - platform: event
      event_type: event_template_reloaded
    - platform: homeassistant
      event: start
    sensor:
      - name: sfups_power
        unique_id: sfups_power
        variables:
          my_entity: sensor.sfups_load
        availability: "{{ my_entity | has_value }}"
        state: >-
          {{int(states(my_entity)) * int(states('sensor.sfups_nominal_real_power')) / 100}}
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power
        
  - sensor:
      - name: EV Charger Energy
        unique_id: ev_charger_energy
        state_class: total
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.ev_charger_last_charge" | has_value }}'
        state: >
            {% if is_state('sensor.ev_charger_last_charge', 'charging') %}
              {{float(state_attr('sensor.ev_charger_last_charge','consumedKwh'),0)}}
            {% endif %}

      - name: Front Door Lights Energy
        unique_id: front_door_lights_energy
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.front_door_down_energy" | has_value }}'
        state: >-
            {{float(states("sensor.front_door_down_energy"),0) + float(states("sensor.front_door_up_energy"),0)}}
      - name: Bedroom 1 Lights Energy
        unique_id: bedroom_1_lights_energy
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.bedroom_1_bulb_1_energy" | has_value }}'
        state: >-
            {{float(states("sensor.bedroom_1_bulb_1_energy"),0) + float(states("sensor.bedroom_1_bulb_2_energy"),0) + float(states("sensor.bedroom_1_bulb_3_energy"),0)}}
      - name: Bedroom 2 Lights Energy
        unique_id: bedroom_2_lights_energy
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.bedroom_2_bulb_1_energy" | has_value }}'
        state: >-
            {{float(states("sensor.bedroom_2_bulb_1_energy"),0) + float(states("sensor.bedroom_2_bulb_2_energy"),0) + float(states("sensor.bedroom_2_bulb_3_energy"),0)}}
      - name: Bedroom 3 Lights Energy
        unique_id: bedroom_3_lights_energy
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.bedside_light_energy" | has_value }}'
        state: >-
            {{float(states("sensor.bedside_light_energy"),0) + float(states("sensor.ceiling_light_energy"),0)}} 
      - name: Living Room Lights Energy
        unique_id: living_room_lights_energy
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: kWh
        availability: '{{ "sensor.side_light_energy" | has_value }}'
        state: >-
            {{float(states("sensor.side_light_energyy"),0) + float(states("sensor.tv_light_energy"),0) + float(states("sensor.main_light_energy"),0) + float(states("sensor.table_light_energy"),0)}} 




mqtt:
  sensor:

    - name: "Home Glow IHD Version"
      unique_id: home_glow_ihd_version
      state_topic: "glow/441793505160/STATE"
      value_template: "{{ value_json['software'] }}"
      device:
        identifiers: ["44:17:93:50:51:60"]
        sw_version: 1.9.1
        manufacturer: "glowmarkt"
        model: "Glow Display and CAD"
        model_id: "smets2"
        name: "Glow - MQTT - Home"

    - name: "Home Electricity Instant"
      unique_id: home_electricity_instant
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'W'
      value_template: "{{ value_json['electricitymeter']['power']['value'] * 1000 }}"
      icon: 'mdi:flash'
      device_class: power
      state_class: measurement
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Electricity"
      unique_id: home_electricity
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['cumulative'] }}"
      icon: 'mdi:counter'
      device_class: energy
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Electricity Daily"
      unique_id: home_electricity_daily
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['day'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Electricity Weekly"
      unique_id: home_electricity_weekly
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['week'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Electricity Price"
      unique_id: home_electricity_price
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'GBP/kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['price']['unitrate'] }}"
      icon: 'mdi:cash'
      device:
        identifiers: ["44:17:93:50:51:60"]

    - name: "Home Gas"
      unique_id: home_gas
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['cumulative'] }}"
      icon: 'mdi:counter'
      device_class: energy
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Gas Daily"
      unique_id: home_gas_daily
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['day'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Gas Weekly"
      unique_id: home_gas_weekly
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['week'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
      device:
        identifiers: ["44:17:93:50:51:60"]
    - name: "Home Gas Price"
      unique_id: home_gas_price
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'GBP/kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['price']['unitrate'] }}"
      icon: 'mdi:cash'
      device:
        identifiers: ["44:17:93:50:51:60"]



sensor:
  - platform: integration
    source: sensor.sfups_power
    name: "Sfups Electricity"
    unique_id: sfups_electricity
    unit_prefix: k
    round: 2
