energy:

homeassistant:
  customize:
    sensor.tc_oil_power:
      friendly_name: "TC Oil Power"
    sensor.tc_oil_usage:
      friendly_name: "TC Oil Instant"
    sensor.tc_oil_price:
      friendly_name: "TC Oil Price"
    sensor.sfups_power:
      friendly_name: "Sfups Power Draw"
    sensor.charger_last_meter_reading:
      state_class: total
      
input_number:
  tc_oil_price:
    name: TC Oil Price
    icon: mdi:cash
    min: 0
    max: 100
    step: .001
    mode: box
    unit_of_measurement: GBP/l

template:
  - trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: time_pattern
      minutes: '0'
      seconds: '15'
    - platform: state
      entity_id: sensor.tc_oil_usage
    - platform: event
      event_type: event_template_reloaded
    - platform: homeassistant
      event: start
    sensor:
      - name: tc_oil_power
        unique_id: tc_oil_power
        state: "{{'%0.2f'| format(float(states('sensor.tc_oil_usage')) * 10.35 * 1000)}}"
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power
        attributes: 
          triggered_at: "{{ now() }}"
  - sensor:
      - name: tc_oil_usage
        unique_id: tc_oil_usage
        state: >-
          {% if is_state('binary_sensor.nest_heating', 'on') %}
            {%set value = 100%}
          {% elif is_state('binary_sensor.nest_hotwater', 'on') %}
            {%set value = 30%}
          {% else %}
            {%set value = 0%}
          {% endif %}
          {{ value * 0.8685 / 100}} 
        unit_of_measurement: 'l/hour'
  - sensor:
      - name: tc_oil_price
        unique_id: tc_oil_price
        state: "{{float(states('input_number.tc_oil_price')) / 10.35}}"
        unit_of_measurement: 'GBP/kWh'
        device_class: monetary
  - sensor:
      - name: sfups_power
        unique_id: sfups_power
        state: "{{int(states('sensor.sfups_load')) * int(states('sensor.sfups_nominal_real_power')) / 100}}"
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power
  - binary_sensor:
      - name: Boiler Firing
        unique_id: boiler_firing
        state: >
          {{ states('sensor.tc_boiler_current_power')|float > 100 }}
  - binary_sensor:
      - name: Boiler Pump
        unique_id: boiler_pump
        state: >
          {{ states('sensor.tc_boiler_current_power')|float > 10 }}
mqtt:
  sensor:
    - name: "TC Electricity Instant"
      unique_id: tc_electricity_instant
      state_topic: "SMART/HILD/84F3EB180551"
      unit_of_measurement: 'W'
      value_template: "{{ value_json['elecMtr']['0702']['04']['00']|int(base=16) }}"
      icon: 'mdi:flash'
      state_class: measurement
    - name: "TC Electricity"
      unique_id: tc_electricity
      state_topic: "SMART/HILD/84F3EB180551"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['elecMtr']['0702']['00']['00']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
      icon: 'mdi:counter'
      device_class: energy
      state_class: total_increasing
      # last_reset_topic: "SMART/HILD/84F3EB180551"
      # last_reset_value_template: homeassistant.util.dt.utc_from_timestamp(0)
    - name: "TC Electricity Daily"
      unique_id: tc_electricity_daily
      state_topic: "SMART/HILD/84F3EB180551"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['elecMtr']['0702']['04']['01']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    - name: "TC Electricity Weekly"
      unique_id: tc_electricity_weekly
      state_topic: "SMART/HILD/84F3EB180551"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['elecMtr']['0702']['04']['30']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    # - name: "TC Electricity Monthly"
    #   state_topic: "SMART/HILD/84F3EB180551"
    #   unit_of_measurement: 'kWh'
    #   value_template: "{{ value_json['elecMtr']['0702']['04']['40']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    #   icon: 'mdi:flash'

    - name: "Home Electricity Instant"
      unique_id: home_electricity_instant
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'W'
      value_template: "{{ value_json['electricitymeter']['power']['value'] * 1000 }}"
      icon: 'mdi:flash'
      state_class: measurement
    - name: "Home Electricity"
      unique_id: home_electricity
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['cumulative'] }}"
      icon: 'mdi:counter'
      device_class: energy
      state_class: total_increasing
    - name: "Home Electricity Daily"
      unique_id: home_electricity_daily
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['day'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    - name: "Home Electricity Weekly"
      unique_id: home_electricity_weekly
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['week'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    - name: "Home Electricity Price"
      unique_id: home_electricity_price
      state_topic: "glow/441793505160/SENSOR/electricitymeter"
      unit_of_measurement: 'GBP/kWh'
      value_template: "{{ value_json['electricitymeter']['energy']['import']['price']['unitrate'] }}"
      icon: 'mdi:cash'

    - name: "Home Gas"
      unique_id: home_gas
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['cumulative'] }}"
      icon: 'mdi:counter'
      device_class: energy
      state_class: total_increasing
    - name: "Home Gas Daily"
      unique_id: home_gas_daily
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['day'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    - name: "Home Gas Weekly"
      unique_id: home_gas_weekly
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['week'] }}"
      icon: 'mdi:flash'
      state_class: total_increasing
    - name: "Home Gas Price"
      unique_id: home_gas_price
      state_topic: "glow/441793505160/SENSOR/gasmeter"
      unit_of_measurement: 'GBP/kWh'
      value_template: "{{ value_json['gasmeter']['energy']['import']['price']['unitrate'] }}"
      icon: 'mdi:cash'

    - name: "Home Glow IHD Version"
      unique_id: home_glow_ihd_version
      state_topic: "glow/441793505160/STATE"
      value_template: "{{ value_json['software'] }}"


sensor:
  - platform: integration
    source: sensor.sfups_power
    name: "Sfups Electricity"
    unique_id: sfups_electricity
    unit_prefix: k
    round: 2
