homeassistant:
  customize:
    switch.home_occupied_the_mews:
      friendly_name: Home - Nest Mode
    switch.home_occupied_tyr_celyn:
      friendly_name: TC - Nest Mode
    switch.home_occupied_workshop:
      friendly_name: Workshop - Nest Mode
    switch.tyr_celyn_thermostat:
      friendly_name: TC - Eco Mode
    switch.tyr_celyn_thermostat_2:
      friendly_name: TC - Hot Water
    binary_sensor.home_occupied_the_mews:
      friendly_name: Home - Presence - Nest
    binary_sensor.home_occupied_tyr_celyn:
      friendly_name: TC - Presence - Nest
    binary_sensor.home_occupied_workshop:
      friendly_name: Workshop - Presence - Nest
    binary_sensor.downstairs:
      friendly_name: Downstairs - Smoke
      icon: mdi:smoke
    binary_sensor.downstairs_2:
      friendly_name: Downstairs - CO
      icon: mdi:molecule-co
    binary_sensor.downstairs_3:
      friendly_name: Downstairs - Nest Occupancy
    binary_sensor.upstairs:
      friendly_name: Upstairs - Smoke
      icon: mdi:smoke
    binary_sensor.upstairs_2:
      friendly_name: Upstairs - CO
      icon: mdi:molecule-co
    binary_sensor.upstairs_3:
      friendly_name: Upstairs - Nest Occupancy
    binary_sensor.tc_dining_room:
      friendly_name: TC - DR - Smoke
      icon: mdi:smoke
    binary_sensor.tc_dining_room_2:
      friendly_name: TC - DR - CO
      icon: mdi:molecule-co
    binary_sensor.tc_living_room:
      friendly_name: TC - LR - Smoke
      icon: mdi:smoke
    binary_sensor.tc_living_room_2:
      friendly_name: TC - LR - CO
      icon: mdi:molecule-co
    binary_sensor.tc_living_room_3:
      friendly_name: TC - LR - Nest Occupancy
    sensor.tyr_celyn_thermostat_temperature:
      friendly_name: Hoobs - Temperature
    sensor.tyr_celyn_thermostat_humidity:
      friendly_name: Hoobs - Humidity
    sensor.tyr_celyn_thermostat_current_temperature:
      friendly_name: Hoobs - Current Temperature
    sensor.tyr_celyn_thermostat_current_humidity:
      friendly_name: Hoobs - Current Humidity
    climate.tyr_celyn_thermostat:
      friendly_name: Hoobs - Thermostat
