homeassistant:
  customize:
    light.bedroom_1:
      friendly_name: Bedroom 1 Lights
    light.bedroom_2:
      friendly_name: Bedroom 2 Lights
    light.bedroom_3:
      friendly_name: Bedroom 3 Lights
    light.living_room:
      friendly_name: Living Room Lights
    light.front_door:
      friendly_name: Front Door Lights
    sensor.living_room_hue_motion_light_level:
      unit_of_measurement: lux
    # binary_sensor.bedroom1_lights_power:
    #   friendly_name: "Bedroom 1 Lights - Power"
    binary_sensor.bedside_light_power:
      friendly_name: "Bedside Light - Power"
    binary_sensor.table_light_power:
      friendly_name: "Table Light - Power"
    binary_sensor.front_door_lights_power:
      friendly_name: "Front Door Light - Power"
    sensor.living_room_hue_lightlevel:
      friendly_name: "Living Room Hue Light Level"
    # sensor.living_room_hue_luxlevel:
    #   friendly_name: "Living Room Hue Lux Level"
    # light.security_lights:
    #   icon: mdi:shield-lock
    # # light.bedroom_1_lights_actual:
    # #   icon: mdi:ceiling-light
    # # light.bedroom_2_lights_actual:
    # #   icon: mdi:ceiling-light
    # light.ceiling_light_actual:
    #   icon: mdi:lamp
    # light.office_lights_actual:
    #   icon: mdi:ceiling-light
    # light.main_light_actual:
    #   icon: mdi:ceiling-light
    # light.side_light_actual:
    #   mdi:wall-sconce-flat
    # light.tv_light_actual:
    #   mdi:wall-sconce-flat

template:
#   - binary_sensor:
#       - name: bedroom1_lights_power
#         unique_id: bedroom1_lights_power
#         device_class: power
#         state: >-
#           {{ not is_state('light.bedroom_1_bulb_1', 'unavailable') or 
#              not is_state('light.bedroom_1_bulb_2', 'unavailable') or
#              not is_state('light.bedroom_1_bulb_3', 'unavailable')
#           }}
  - binary_sensor:
      - name: bedside_light_power
        unique_id: bedside_light_power
        device_class: power
        state: >-
          {{ not is_state('light.bedside_light', 'unavailable') }}
  - binary_sensor:
      - name: table_light_power
        unique_id: table_light_power
        device_class: power
        state: >-
          {{ not is_state('light.table_light', 'unavailable') }}
  - binary_sensor:
      - name: front_door_lights_power
        unique_id: front_door_lights_power
        device_class: power
        state: >-
          {{ not is_state('light.front_door_down', 'unavailable') or
             not is_state('light.front_door_up', 'unavailable')
          }}

  - sensor:
      - name: living_room_hue_lightlevel
        unique_id: living_room_hue_lightlevel
        state: "{{state_attr('sensor.living_room_hue_motion_light_level','light_level')}}"
        unit_of_measurement: 'lumens'

# light:
#   - platform: switch
#     name: zwave_living_room_main_light_switch
#     entity_id: switch.zwave_living_room_main_light_switch
#   - platform: switch
#     name: zwave_living_room_side_light_switch
#     entity_id: switch.zwave_living_room_side_light_switch
#   - platform: group
#     name: Security Lights
#     unique_id: security_lights
#     # icon: mdi:shield-lock
#     entities:
#       - light.main_light
#       - light.side_light
#       - light.table_light
#       - light.bedside_light
#       - light.ceiling_light
#       - light.office_light
# #   - platform: group
# #     name: Bedroom 1 Lights Actual
# #     unique_id: bedroom_1_lights_actual
# #     # icon: mdi:ceiling-light
# #     all: false
# #     entities:
# #     #   - binary_sensor.bedroom1_lights_power
# #       - light.bedroom_1_bulb_1
# #       - light.bedroom_1_bulb_2
# #       - light.bedroom_1_bulb_3
# #   - platform: group
# #     name: Bedroom 2 Lights Actual
# #     unique_id: bedroom_2_lights_actual
# #     # icon: mdi:ceiling-light
# #     all: false
# #     entities:
# #     #   - binary_sensor.bedroom2_lights_power
# #       - light.bedroom_2_bulb_1
# #       - light.bedroom_2_bulb_2
# #       - light.bedroom_2_bulb_3    
#   - platform: group
#     name: Ceiling Lights Actual
#     unique_id: ceiling_light_actual
#     # icon: mdi:lamp
#     all: true
#     entities:
#     #   - binary_sensor.ceiling_light_power
#       - light.ceiling_light
#   - platform: group
#     name: Office Lights Actual
#     unique_id: office_lights_actual
#     # icon: mdi:ceiling-light
#     all: true
#     entities:
# #      - binary_sensor.office_lights_power
#       - light.office      
#   - platform: group
#     name: Main Light Actual
#     unique_id: main_light_actual
#     # icon: mdi:ceiling-light
#     all: true
#     entities:
#       - light.zwave_living_room_main_light_switch
#       - light.main_light
#   - platform: group
#     name: Side Light Actual
#     unique_id: side_light_actual
#     # icon: mdi:wall-sconce-flat
#     all: true
#     entities:
#       - light.zwave_living_room_side_light_switch
#       - light.side_light
#   - platform: group
#     name: TV Light Actual
#     unique_id: tv_light_actual
#     # icon: mdi:wall-sconce-flat
#     all: true
#     entities:
#       - light.zwave_living_room_side_light_switch
#       - light.tv_light

group:
  security_lights:
    name: Security Lights
    icon: mdi:shield-lock
    entities:
      - light.main_light
      - light.side_light
      - light.table_light
      - light.bedside_light
      - light.ceiling_light
      - light.office_light
    
  main_light_actual:
    name: Main Light Actual
    icon: mdi:ceiling-light
    all: true
    entities:
      - switch.living_room_virtual_switch_1
      - light.main_light
  side_light_actual:
    name: Side Light Actual
    icon: mdi:wall-sconce-flat
    all: true
    entities:
      - switch.living_room_virtual_switch_2
      - light.side_light
  tv_light_actual:
    name: TV Light Actual
    icon: mdi:wall-sconce-flat
    all: true
    entities:
      - switch.living_room_virtual_switch_2
      - light.tv_light
  table_light_actual:
    name: Table Light Actual
    icon: mdi:lamp
    all: true
    entities:
      - binary_sensor.table_light_power
      - light.table_light
  living_room_lights_actual:
    name: Living Room Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
      - group.main_light_actual
      - group.side_light_actual
      - group.tv_light_actual
      - group.table_light_actual
  bedroom_1_lights_actual:
    name: Bedroom 1 Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
    #   - binary_sensor.bedroom1_lights_power
      - light.bedroom_1_bulb_1
      - light.bedroom_1_bulb_2
      - light.bedroom_1_bulb_3
  bedroom_2_lights_actual:
    name: Bedroom 2 Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
    #   - binary_sensor.bedroom2_lights_power
      - light.bedroom_2_bulb_1
      - light.bedroom_2_bulb_2
      - light.bedroom_2_bulb_3
  bedside_light_actual:
    name: Bedside Light Actual
    icon: mdi:lamp
    all: true
    entities:
      - binary_sensor.bedside_light_power
      - light.bedside_light
  ceiling_light_actual:
    name: Ceiling Lights Actual
    icon: mdi:lamp
    all: true
    entities:
    #   - binary_sensor.ceiling_light_power
      - light.ceiling_light
  bedroom_3_lights_actual:
    name: Bedroom 3 Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
      - group.bedside_light_actual
      - group.ceiling_light_actual
  office_lights_actual:
    name: Office Lights Actual
    icon: mdi:ceiling-light
    all: true
    entities:
#      - binary_sensor.office_lights_power
      - light.office
  front_door_lights_actual:
    name: Front Door Lights Actual
    icon: mdi:wall-sconce-flat
    all: true
    entities:
      - binary_sensor.front_door_lights_power
      - light.front_door
  house_lights_actual:
    name: House Lights Actual
    icon: mdi:ceiling-lamp-multiple
    all: false
    entities:
      - group.bedroom_1_lights_actual
      - group.bedroom_2_lights_actual
      - group.bedroom_3_lights_actual
      - group.living_room_lights_actual
      - group.office_lights_actual
      
    

input_select:
  fireplace_lights_mode:
    name: Fireplace Mode
    options:
      - Evening Chill
      - Evening Friends
  living_room_scenes:
    name: Living Room Scenes
    options:
      - Evening Chill
      - Evening Friends
      - Meal Time
      - Normal
      - Reading
      - None
    initial: None
  bedroom_2_scenes:
    name: Bedroom 2 Scenes
    options:
      - Zoom
      - Relax
      - Flash
      - None
    initial: None
    

timer:
  lights_living_room:
    name: Time to Living Room Unoccupied
    duration: '00:15:00'
    restore: true
  lights_office:
    name: Time to Office Unoccupied
    duration: '00:05:00'  
    restore: true
  lights_front_door:
    name: Time to Front Door Lights Off
    duration: '00:05:00'
    restore: true
    