homeassistant:
  customize:
    binary_sensor.living_room_occupancy:
      friendly_name: 'Living Room Motion' 
    binary_sensor.kitchen_occupancy:
      friendly_name: 'Kitchen Motion' 
    binary_sensor.downstairs_occupancy:
      friendly_name: 'Downstairs Motion' 
    binary_sensor.upstairs_occupancy:
      friendly_name: 'Upstairs Motion' 
    sensor.front_door_person_motion:
      friendly_name: "Front Door Person Motion"


template:
  - binary_sensor:
      - name: living_room_occupancy
        unique_id: living_room_occupancy
        state: >-
          {{ is_state('binary_sensor.living_room_hue_motion_motion', 'on')
          or is_state('binary_sensor.geniushub_living_room_occupancy', 'on') }}
        device_class: motion
  - binary_sensor:
      - name: kitchen_occupancy
        unique_id: kitchen_occupancy
        state: >-
          {{ is_state('binary_sensor.kitchen_pir', 'on')
          or is_state('binary_sensor.geniushub_kitchen_occupancy', 'on') }}
        device_class: motion
  - binary_sensor:
      - name: downstairs_occupancy
        unique_id: downstairs_occupancy
        state: >-
          {{ is_state('binary_sensor.living_room_hue_motion_motion', 'on')
          or is_state('binary_sensor.geniushub_dining_room_occupancy', 'on')
          or is_state('binary_sensor.geniushub_living_room_occupancy', 'on')
          or is_state('binary_sensor.kitchen_pir', 'on')
          or is_state('binary_sensor.geniushub_kitchen_occupancy', 'on') }}
        device_class: motion
  - binary_sensor:
      - name: upstairs_occupancy
        unique_id: upstairs_occupancy
        state: >-
          {{ is_state('binary_sensor.geniushub_bedroom1_occupancy', 'on')
          or is_state('binary_sensor.geniushub_bedroom2_occupancy', 'on')
          or is_state('binary_sensor.geniushub_bedroom3_occupancy', 'on')
          or is_state('binary_sensor.zwave_office_fibaro_motion', 'on') }}
        device_class: motion

  - sensor:
    - name: front_door_person_motion
      unique_id: front_door_person_motion
      state: >-
          {% if is_state('binary_sensor.front_door_person_detected', 'on') %}
            person
          {% elif is_state('binary_sensor.front_door_object_detected', 'on') %}
            on
          {% else %}
            off
          {% endif %}  

input_boolean:
  office_motion:
    name: Office Motion
    icon: mdi:transition


group:
#   presence_all:
#     name: Presence - All
#     icon: mdi:account-group
#     entities:
#       - person.benjamin_selwyn
#       - person.clare_selwyn
#       - person.roger_selwyn
  living_room_occupancy:
    entities:
      - binary_sensor.living_room_hue_motion_motion
      - binary_sensor.geniushub_living_room_occupancy


input_select:
  location_mode:
    name: Location Mode
    options:
      - Home
      - Away
      - Night
      - Evening Time

sensor:
  - platform: template
    sensors:
      location_mode:
        unique_id: location_mode
        value_template: "{{ states('input_select.location_mode') }}"
        friendly_name_template: >-
          {{ states('input_select.location_mode') }}
        entity_picture_template: >-
          {% if is_state('input_select.location_mode', 'Home') %}
            /local/icons/home.png
          {% elif is_state('input_select.location_mode', 'Away') %}
            /local/icons/shield-lock.png
          {% elif is_state('input_select.location_mode', 'Night') %}
            /local/icons/weather-night.png
          {% elif is_state('input_select.location_mode', 'Evening Time') %}
            /local/icons/weather-sunset.png
          {% endif %}

timer:
  night:
    name: Time to Night
    duration: '00:15:00'
    restore: true
  away:
    name: Time to Away
    duration: '00:07:00'
    restore: true
    
