sensor:
    - platform: snmp
      unique_id: nas_volume_1_disk_space
      name: 'NAS Volume 1 Disk Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.6.1
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_2_disk_space
      name: 'NAS Volume 2 Disk Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.6.2
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_3_disk_space
      name: 'NAS Volume 3 Disk Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.6.3
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_4_disk_space
      name: 'NAS Volume 4 Disk Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.6.4
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_1_free_space
      name: 'NAS Volume 1 Free Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.7.1
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_2_free_space
      name: 'NAS Volume 2 Free Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.7.2
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_3_free_space
      name: 'NAS Volume 3 Free Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.7.3
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    - platform: snmp
      unique_id: nas_volume_4_free_space
      name: 'NAS Volume 4 Free Space'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.7.4
      version: '2c'
      value_template: '{{((value | int) / 1024) | round(2)}}'
      unit_of_measurement: 'Tb'
      
    # - platform: snmp
    #   unique_id: nas_cpu_usage
    #   name: 'NAS CPU Usage'
    #   host: 192.168.1.30
    #   community: public
    #   baseoid: 1.3.6.1.4.1.44738.2.7.1.1.2.0
    #   version: '2c'
    #   unit_of_measurement: '%'
    
    - platform: snmp
      unique_id: nas_serial_number
      name: 'NAS Serial Number'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.1.1.0
      version: '2c'
    
    - platform: snmp
      unique_id: nas_adm_version
      name: 'NAS ADM Version'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.1.2.0
      version: '2c'
      
    - platform: snmp
      unique_id: nas_model
      name: 'NAS Model'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.2.1.0
      version: '2c'
      
    - platform: snmp
      unique_id: nas_uptime
      name: 'NAS Uptime'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.1.4.0
      version: '2c'
      
    - platform: snmp
      unique_id: nas_ip
      name: 'NAS IP'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.3.1.1.4.1
      version: '2c'
    
    - platform: snmp
      unique_id: nas_free_memory
      name: 'NAS Free Memory'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.2.5.0
      version: '2c'
      unit_of_measurement: 'Mb'
      
    - platform: snmp
      unique_id: nas_hdd_1_details
      name: 'NAS HDD 1 Details'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.3.1
      version: '2c'
      
    - platform: snmp
      unique_id: nas_hdd_2_details
      name: 'NAS HDD 2 Details'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.3.2
      version: '2c'
      
    - platform: snmp
      unique_id: nas_hdd_3_details
      name: 'NAS HDD 3 Details'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.3.3
      version: '2c'
      
    - platform: snmp
      unique_id: nas_hdd_4_details
      name: 'NAS HDD 4 Details'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.3.4
      version: '2c'
      
    - platform: snmp
      unique_id: nas_hdd_1_status
      name: 'NAS HDD 1 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.5.1
      version: '2c'
      
    - platform: snmp
      unique_id: nas_hdd_2_status
      name: 'NAS HDD 2 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.5.2
      version: '2c'
    
    - platform: snmp
      unique_id: nas_hdd_3_status
      name: 'NAS HDD 3 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.5.3
      version: '2c'
    
    - platform: snmp
      unique_id: nas_hdd_4_status
      name: 'NAS HDD 4 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.5.4
      version: '2c'
    
    - platform: snmp
      unique_id: nas_hdd_1_temperature
      name: 'NAS HDD 1 Temperature'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.6.1
      version: '2c'
      unit_of_measurement: '째C'
      
    - platform: snmp
      unique_id: nas_hdd_2_temperature
      name: 'NAS HDD 2 Temperature'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.6.2
      version: '2c'
      unit_of_measurement: '째C'
     
    - platform: snmp
      unique_id: nas_hdd_3_temperature
      name: 'NAS HDD 3 Temperature'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.6.3
      version: '2c'
      unit_of_measurement: '째C'
     
    - platform: snmp
      unique_id: nas_hdd_4_temperature
      name: 'NAS HDD 4 Temperature'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.4.1.1.6.4
      version: '2c'
      unit_of_measurement: '째C'
     
    - platform: snmp
      unique_id: nas_volume_1_status
      name: 'NAS Volume 1 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.4.1
      version: '2c'
    
    - platform: snmp
      unique_id: nas_volume_2_status
      name: 'NAS Volume 2 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.4.2
      version: '2c'
    
    - platform: snmp
      unique_id: nas_volume_3_status
      name: 'NAS Volume 3 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.4.3
      version: '2c'
    
    - platform: snmp
      unique_id: nas_volume_4_status
      name: 'NAS Volume 4 Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.5.1.1.4.4
      version: '2c'
    
    - platform: snmp
      unique_id: nas_adm_update_status
      name: 'NAS ADM Update Status'
      host: 192.168.1.30
      community: public
      baseoid: 1.3.6.1.4.1.44738.1.7.0
      version: '2c'