homeassistant:
  customize:
    switch.living_room_fibaro_switch_switch:
      friendly_name: Main Light Switch
      icon: mdi:power-cycle
    switch.living_room_fibaro_switch_switch_2:
      friendly_name: Side Light Switch
      icon: mdi:power-cycle
    sensor.motion_sensor_illuminance:
      unit_of_measurement: lx
    binary_sensor.zwave_office_fibaro_motion:
      friendly_name: Office Fibaro Motion
    sensor.zwave_office_fibaro_illuminance:
      friendly_name: 'Office Fibaro Illuminance'
    sensor.zwave_office_fibaro_temperature:
      friendly_name: 'Office Fibaro Temperature'
    switch.zwave_living_room_main_light_switch:
      friendly_name: Main Light Switch
    switch.zwave_living_room_side_light_switch:
      friendly_name: Fireplace Light Switch
    
      

template:
  - binary_sensor:
      - name: zwave_office_fibaro_motion
        unique_id: zwave_office_fibaro_motion
        device_class: motion
        state: "{{ is_state('binary_sensor.motion_sensor_home_security_motion_detection', 'on') }}"

  - sensor:
      - name: zwave_office_fibaro_illuminance
        unique_id: wave_office_fibaro_illuminance
        state: "{{ '%.0f'%(states('sensor.motion_sensor_illuminance') | float(0)) }}"
        unit_of_measurement: 'lx'
        device_class: illuminance
  - sensor:
      - name: zwave_office_fibaro_temperature
        unique_id: zwave_office_fibaro_temperature
        state: "{{ '%.0f'%(states('sensor.motion_sensor_air_temperature') | float(0)) }}"
        unit_of_measurement: '°C'
        device_class: temperature

switch:
  - platform: template
    switches:
      zwave_living_room_main_light_switch:
        value_template: "{{ is_state('switch.double_switch_2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.double_switch_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.double_switch_2
      zwave_living_room_side_light_switch:
        value_template: "{{ is_state('switch.double_switch_2_2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.double_switch_2_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.double_switch_2_2
