- id: set_theme_at_startup
  alias: Set theme at startup
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: ios-dark-mode
#- id: christmas_lights_on
#  alias: Christmas Lights - Turn On
#  description: ''
#  trigger:
#  - event: sunset
#    platform: sun
#  condition: []
#  action:
#  - device_id: b73e7c9fb1ff41288cfaef48106d1071
#    domain: switch
#    entity_id: switch.christmas_lights
#    type: turn_on
#- id: christmas_lights_off
#  alias: Christmas Lights - Turn Off
#  description: ''
#  trigger:
#  - at: '23:30'
#    platform: time
#  condition: []
#  action:
#  - device_id: b73e7c9fb1ff41288cfaef48106d1071
#    domain: switch
#    entity_id: switch.christmas_lights
#    type: turn_off
