- platform: template
  sensors:
    bedroom1_lights_power:
      friendly_name: "Bedroom 1 Lights - Power"
      value_template: >-
        {{ not is_state('light.bedroom_1_bulb_1', 'unavailable') }}
      icon_template: >-
        {% if is_state('binary_sensor.bedroom1_lights_power', 'on') %}
          mdi:power
        {% else %}
          mdi:power-off
        {% endif %}
    bedroom2_lights_power:
      friendly_name: "Bedroom 2 Lights - Power"
      value_template: >-
        {{ not is_state('light.bedroom_2_bulb_1', 'unavailable') }}
      icon_template: >-
        {% if is_state('binary_sensor.bedroom2_lights_power', 'on') %}
          mdi:power
        {% else %}
          mdi:power-off
        {% endif %}
    bedroom3_lights_power:
      friendly_name: "Bedroom 3 Lights - Power"
      value_template: >-
        {{ not is_state('light.bedroom_light', 'unavailable') }}
      icon_template: >-
        {% if is_state('binary_sensor.bedroom3_lights_power', 'on') %}
          mdi:power
        {% else %}
          mdi:power-off
        {% endif %}
    office_lights_power:
      friendly_name: "Office 3 Lights - Power"
      value_template: >-
        {{ not is_state('light.office_light', 'unavailable') }}
      icon_template: >-
        {% if is_state('binary_sensor.office_lights_power', 'on') %}
          mdi:power
        {% else %}
          mdi:power-off
        {% endif %}
    table_light_power:
      friendly_name: "Table Light - Power"
      value_template: >-
        {{ not is_state('light.table_light', 'unavailable') }}
      icon_template: >-
        {% if is_state('binary_sensor.table_light_power', 'on') %}
          mdi:power
        {% else %}
          mdi:power-off
        {% endif %}

    geniushub_living_room_occupancy:
      value_template: "{{ state_attr('climate.living_room', 'status').occupied == true }}"
      device_class: motion
      friendly_name: 'Living Room Genius Motion' 
    geniushub_kitchen_occupancy:
      value_template: "{{ state_attr('climate.kitchen', 'status').occupied == true }}"
      device_class: motion
      friendly_name: 'Kitchen Genius Motion' 
    geniushub_bedroom1_occupancy:
      value_template: "{{ state_attr('climate.bedroom_1', 'status').occupied == true }}"
      device_class: motion
      friendly_name: 'Bedroom 1 Genius Motion' 
    geniushub_bedroom2_occupancy:
      value_template: "{{ state_attr('climate.bedroom_2', 'status').occupied == true }}"
      device_class: motion
      friendly_name: 'Bedroom 2 Genius Motion' 
    geniushub_bedroom3_occupancy:
      value_template: "{{ state_attr('climate.bedroom_3', 'status').occupied == true }}"
      device_class: motion
      friendly_name: 'Bedroom 3 Genius Motion' 

    living_room_occupancy:
      value_template: >-
        {{ is_state('binary_sensor.zwave_living_room_fibaro_motion', 'on')
        or state_attr('climate.living_room', 'status').occupied == true }}
      device_class: motion
      friendly_name: 'Living Room Occupancy' 
    kitchen_occupancy:
      value_template: >-
        {{ is_state('binary_sensor.kitchen_pir', 'on')
        or state_attr('climate.kitchen', 'status').occupied == true }}
      device_class: motion
      friendly_name: 'Kitchen Occupancy' 
    downstairs_occupancy:
      value_template: >-
        {{ is_state('binary_sensor.zwave_living_room_fibaro_motion', 'on')
        or state_attr('climate.living_room', 'status').occupied == true
        or is_state('binary_sensor.kitchen_pir', 'on')
        or state_attr('climate.kitchen', 'status').occupied == true }}
      device_class: motion
      friendly_name: 'Downstairs Occupancy' 
    upstairs_occupancy:
      value_template: >-
        {{ state_attr('climate.bedroom_1', 'status').occupied == true
        or state_attr('climate.bedroom_2', 'status').occupied == true
        or state_attr('climate.bedroom_3', 'status').occupied == true }}
      device_class: motion
      friendly_name: 'Upstairs Occupancy' 

    hue:
      friendly_name: "Hue"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.hue', 'on') }}"
    internet:
      friendly_name: "Internet"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.internet', 'on') }}"

    zwave_living_room_fibaro_motion:
      device_class: motion
      friendly_name: Living Room Fibaro Motion
      value_template: "{{ is_state('binary_sensor.fgms001_zw5_motion_sensor_home_security_motion_detected', 'on') }}"

    tyrcelyn_presence_all:
      friendly_name: "TC - Presence - All"
      device_class: presence
      value_template: "{{ is_state('input_boolean.tyrcelyn_presence_all', 'on') }}"
    # tyrcelyn_presence_cleaner:
    #   friendly_name: "TC - Presence - Cleaner"
    #   device_class: presence
    #   value_template: "{{ is_state('input_boolean.tyrcelyn_presence_cleaner', 'on') }}"
    tyrcelyn_bookings:
      friendly_name: "TC - Booked"
      device_class: presence
      value_template: "{{ is_state('calendar.bookings', 'on') }}"
    tyrcelyn_guests:
      friendly_name: "TC - Guests"
      device_class: presence
      value_template: "{{ is_state('input_boolean.tyrcelyn_guests', 'on') }}"
    tyrcelyn_utility_motion:
      friendly_name: "TC - Utility Motion"
      device_class: motion
      value_template: "{{ is_state('input_boolean.tyrcelyn_utility_motion', 'on') }}"


#- platform: ping
#  name: hue
#  host: !secret hue_host
#  scan_interval: 10
#- platform: ping
#  name: internet
#  host: 8.8.8.8
#  scan_interval: 10
