# - platform:  skyq
#   name: Sky Q Mini
#   host: !secret skyqmini_host
#   sources:
#       BBCOne: '1,1,5'
#       BBCTwo: '1,0,2'
#       SkyAtlantic: '1,0,8'
#       SkyOne: '1,0,6'
#       SkyNews: '5,0,1'
# - platform:  skyq
#   name: Sky Q
#   host: !secret skyq_host
#   sources:
#       BBCOne: '1,1,5'
#       BBCTwo: '1,0,2'
#       SkyAtlantic: '1,0,8'
#       SkyOne: '1,0,6'
#       SkyNews: '5,0,1'
- platform: braviatv_psk
  host: !secret tv_host
  psk: !secret tv_psk
  mac: !secret tv_mac
  amp: False
  android: True
  user_labels: True
  sourcefilter:
    - HDMI
  name: SFTV
 