- platform: websocket_api
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
#- platform: command_line
#  name: CPU Temperature
#  command: "cat /sys/class/thermal/thermal_zone0/temp"
#  unit_of_measurement: "°C"
#  value_template: '{{ value | multiply(0.001) | round(1) }}'
# - platform: command_line
#   name: Addons
#   scan_interval: 3600
#   command: "ha supervisor info --raw-json"
# Sensor to track available updates for supervisor & addons
# - platform: command_line
#   name: Supervisor updates
#   scan_interval: 3600
#   command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"addons":[.data.addons[]]}'''
#   json_attributes:
#   - addons
- platform: command_line
  name: Supervisor addons
  scan_interval: 3600
  command: 'curl http://supervisor/supervisor/info -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"addons":[.data.addons[]]}'''
  value_template: "{{ value_json.addons | length }}"
  json_attributes:
    - addons

#- platform: time_date
#  display_options:
#    - 'time'
#    - 'date'
#    - 'date_time'
#    - 'date_time_iso'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'
#- platform: badnest

- platform: template
  sensors:
    tc_current_temperature:
      friendly_name: "Ty'r Celyn Current Temperature"
      value_template: "{{ state_attr('climate.tyr_celyn_thermostat', 'current_temperature') }}"
      unit_of_measurement: °C
    tc_set_temperature:
      friendly_name: "Ty'r Celyn Set Temperature"
      value_template: "{{ state_attr('climate.tyr_celyn_thermostat', 'temperature') }}"
      unit_of_measurement: °C
    tc_hvac_action:
      friendly_name: "Ty'r Celyn HVAC Action"
      value_template: "{{ state_attr('climate.tyr_celyn_thermostat', 'hvac_action') }}"
      unit_of_measurement: none
    tc_humidity:
      friendly_name: "TC - Humidity"
      value_template: "{{ state_attr('climate.tyr_celyn_thermostat', 'current_humidity') }}"
      unit_of_measurement: '%'
    geniushub_living_room_luminance:
      value_template: "{{ '%.0f'%(state_attr('sensor.room_sensor_20', 'state').luminance | float) }}"
      friendly_name: 'Living Room Genius Illuminance' 
      unit_of_measurement: 'lux'
      device_class: illuminance
    geniushub_kitchen_luminance:
      value_template: "{{ '%.0f'%(state_attr('sensor.room_sensor_19', 'state').luminance | float) }}"
      friendly_name: 'Kitchen Genius Illuminance' 
      unit_of_measurement: 'lux'
      device_class: illuminance
    geniushub_bedroom1_luminance:
      value_template: "{{ '%.0f'%(state_attr('sensor.room_sensor_30', 'state').luminance | float) }}"
      friendly_name: 'Bedroom 1 Genius Illuminance' 
      unit_of_measurement: 'lux'
      device_class: illuminance
    geniushub_bedroom2_luminance:
      value_template: "{{ '%.0f'%(state_attr('sensor.room_sensor_21', 'state').luminance | float) }}"
      friendly_name: 'Bedroom 2 Genius Illuminance' 
      unit_of_measurement: 'lux'
      device_class: illuminance
    geniushub_bedroom3_luminance:
      value_template: "{{ '%.0f'%(state_attr('sensor.room_sensor_22', 'state').luminance | float) }}"
      friendly_name: 'Bedroom 3 Genius Illuminance' 
      unit_of_measurement: 'lux'
      device_class: illuminance

    location_mode:
      value_template: "{{ states('input_select.location_mode') }}"
      friendly_name_template: >-
        {{ states('input_select.location_mode') }}
      entity_picture_template: >-
        {% if is_state('input_select.location_mode', 'Home') %}
          /local/icons/home.png
        {% elif is_state('input_select.location_mode', 'Away') %}
          /local/icons/shield-lock.png
        {% elif is_state('input_select.location_mode', 'Night') %}
          /local/icons/weather-night.png
        {% elif is_state('input_select.location_mode', 'Evening Time') %}
          /local/icons/weather-sunset.png
        {% endif %}
    # bookings:
    #   value_template: "{{ states('calendar.bookings') }}"
    #   friendly_name_template: >-
    #     {% if is_state('calendar.bookings', 'on') %}
    #       Booked
    #     {% else %}
    #       Empty
    #     {% endif %}
    #   entity_picture_template: >-
    #     {% if is_state('calendar.bookings', 'on') %}
    #       /local/icons/home.png
    #     {% else %}
    #       /local/icons/home-outline.png
    #     {% endif %}


    zwave_living_room_fibaro_illuminance:
      value_template: "{{ '%.0f'%(states('sensor.fgms001_zw5_motion_sensor_illuminance') | float) }}"
      friendly_name: 'Living Room Fibaro Illuminance'
      unit_of_measurement: 'lux'
      device_class: illuminance
