- platform: template
  switches:
    zwave_living_room_main_light_switch:
      friendly_name: Main Light Switch
      value_template: "{{ is_state('switch.fibaro_double_switch_2_instance_1_switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.fibaro_double_switch_2_instance_1_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.fibaro_double_switch_2_instance_1_switch
    zwave_living_room_side_light_switch:
      friendly_name: Side Light Switch
      value_template: "{{ is_state('switch.fibaro_double_switch_2_instance_2_switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.fibaro_double_switch_2_instance_2_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.fibaro_double_switch_2_instance_2_switch
