homeassistant:
  customize:
    light.bedroom_1:
      friendly_name: Bedroom 1 Lights
    light.bedroom_2:
      friendly_name: Bedroom 2 Lights
    light.bedroom_3:
      friendly_name: Bedroom 3 Lights
    light.living_room:
      friendly_name: Living Room Lights
    sensor.living_room_hue_motion_light_level:
      unit_of_measurement: lux

binary_sensor:
  - platform: template
    sensors:
      bedroom1_lights_power:
        friendly_name: "Bedroom 1 Lights - Power"
        value_template: >-
          {{ not is_state('light.bedroom_1_bulb_1', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.bedroom1_lights_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}
      bedroom2_lights_power:
        friendly_name: "Bedroom 2 Lights - Power"
        value_template: >-
          {{ not is_state('light.bedroom_2_bulb_1', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.bedroom2_lights_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}
      ceiling_light_power:
        friendly_name: "Ceiling Light - Power"
        value_template: >-
          {{ not is_state('light.ceiling_light', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.ceiling_light_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}
      bedside_light_power:
        friendly_name: "Bedside Light - Power"
        value_template: >-
          {{ not is_state('light.bedside_light', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.bedside_light_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}
      office_lights_power:
        friendly_name: "Office Lights - Power"
        value_template: >-
          {{ not is_state('light.office_light', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.office_lights_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}
      table_light_power:
        friendly_name: "Table Light - Power"
        value_template: >-
          {{ not is_state('light.table_light', 'unavailable') }}
        icon_template: >-
          {% if is_state('binary_sensor.table_light_power', 'on') %}
            mdi:power
          {% else %}
            mdi:power-off
          {% endif %}

group:
  security_lights:
    name: Security Lights
    icon: mdi:shield-lock
    entities:
      - light.main_light
      - light.fireplace
      - light.table_light
      - light.bedside_light
      - light.ceiling_light
      - light.office_light
    
  main_light_actual:
    name: Main Light Actual
    icon: mdi:ceiling-light
    all: true
    entities:
      - switch.zwave_living_room_main_light_switch
      - light.main_light
  side_light_actual:
    name: Side Light Actual
    icon: mdi:wall-sconce-flat
    all: true
    entities:
      - switch.zwave_living_room_side_light_switch
      - light.side_light
  tv_light_actual:
    name: TV Light Actual
    icon: mdi:wall-sconce-flat
    all: true
    entities:
      - switch.zwave_living_room_side_light_switch
      - light.tv_light
  table_light_actual:
    name: Table Light Actual
    icon: mdi:lamp
    all: true
    entities:
      - binary_sensor.table_light_power
      - light.table_light
  living_room_lights_actual:
    name: Living Room Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
      - group.main_light_actual
      - group.side_light_actual
      - group.tv_light_actual
      - group.table_light_actual
  bedroom_1_lights_actual:
    name: Bedroom 1 Lights Actual
    icon: mdi:ceiling-light
    all: true
    entities:
      - binary_sensor.bedroom1_lights_power
      - light.bedroom_1
  bedroom_2_lights_actual:
    name: Bedroom 2 Lights Actual
    icon: mdi:ceiling-light
    all: true
    entities:
      - binary_sensor.bedroom2_lights_power
      - light.bedroom_2
  bedside_light_actual:
    name: Bedside Light Actual
    icon: mdi:lamp
    all: true
    entities:
      - binary_sensor.bedside_light_power
      - light.bedside_light
  ceiling_light_actual:
    name: Bedroom 3 Lights Actual
    icon: mdi:lamp
    all: true
    entities:
      - binary_sensor.ceiling_light_power
      - light.ceiling_light
  bedroom_3_lights_actual:
    name: Bedroom 3 Lights Actual
    icon: mdi:ceiling-light
    all: false
    entities:
      - group.bedside_light_actual
      - group.ceiling_light_actual
  office_lights_actual:
    name: Office Lights Actual
    icon: mdi:ceiling-light
    all: true
    entities:
      - binary_sensor.office_lights_power
      - light.office

input_number:
  security_lights:
    min: 0
    max: 10
    step: 1

input_select:
  fireplace_lights_mode:
    name: Fireplace Mode
    options:
      - Evening Chill
      - Evening Friends

sensor:
  - platform: template
    sensors:
      security_lights:
        friendly_name: "Security Lights"
        value_template: >
          {{states('input_number.security_lights')|int}}
      living_room_hue_lightlevel:
        friendly_name: "Living Room Hue Light Level"
        value_template: "{{state_attr('sensor.living_room_hue_motion_light_level', 'lightlevel')|int}}"
      living_room_hue_battery_level:
        friendly_name: "Living Room Hue battery level"
        value_template: "{{state_attr('sensor.living_room_hue_motion_light_level', 'battery_level')|int}}"
        unit_of_measurement: '%'
        device_class: battery


timer:
  lights_living_room:
    name: Time to Lights Off
    duration: '00:15:00'
  lights_office:
    name: Time to Office Lights Off
    duration: '00:05:00'