nest:
  client_id: !secret nest-client-id
  client_secret: !secret nest-client-secret
  project_id: !secret nest-project-id
  subscriber_id: !secret nest-subscriber-id

binary_sensor:
  - platform: template
    sensors:
      nest_heating:
        friendly_name: TC - Heating
        device_class: heat
        value_template: >-
          {{ is_state_attr('climate.tyr_celyn', 'hvac_action', 'heating') }}
      nest_hotwater:
        friendly_name: TC - Hot Water
        device_class: heat
        value_template: >-
          {{ is_state('switch.tyr_celyn_thermostat_2', 'on') }}
      nest_heating_manual:
        friendly_name: TC - Heating Manual
        device_class: heat
        value_template: >-
          {% if state_attr('climate.tyr_celyn', 'hvac_action') == 'heating' and
             state_attr('climate.tyr_celyn', 'temperature') is defined and
             state_attr('climate.tyr_celyn', 'current_temperature') > state_attr('climate.tyr_celyn', 'temperature') + 0.5 %}
            true
          {% else %}
            false
          {% endif %}
sensor:
  - platform: template
    sensors:
      nest_heating:
        device_class: temperature
        unit_of_measurement: °C
        value_template: >-
          {% if state_attr('climate.tyr_celyn', 'hvac_action') == 'heating' %}
            {{ state_attr('climate.tyr_celyn', 'current_temperature') }}
          {% else %}
            0
          {% endif %}
      nest_hotwater:
        unit_of_measurement: "on"
        value_template: >-
          {% if is_state('switch.tyr_celyn_thermostat_2', 'on') %}
            1
          {% else %}
            0
          {% endif %}
      nest_hvac:
        value_template: >-
          {{ state_attr('climate.tyr_celyn', 'hvac_action')}}
      nest_current_temperature:
        device_class: temperature
        unit_of_measurement: °C
        value_template: >-
          {{ state_attr('climate.tyr_celyn', 'current_temperature')}}
      nest_set_temperature:
        device_class: temperature
        unit_of_measurement: °C
        value_template: >-
          {{ state_attr('climate.tyr_celyn', 'temperature')}}
