homeassistant:
  customize:
    binary_sensor.tyrcelyn_bookings:
      friendly_name: "TC - Booked"
    binary_sensor.tyrcelyn_guests:
      friendly_name: "TC - Guests"
    binary_sensor.tyrcelyn_presence_all:
      friendly_name: "TC - Presence - All"
    binary_sensor.tyrcelyn_presence_cleaner:
      friendly_name: "TC - Presence - Cleaner"
    binary_sensor.tyrcelyn_utility_motion:
      friendly_name: "TC - Utility Motion"

notify:
  - platform: file
    name: tyrcelyn
    filename: logs/tyrcelyn.csv
    timestamp: true

sensor:
  - platform: template
    sensors:
      tc_current_temperature:
        friendly_name: "Ty'r Celyn Current Temperature"
        value_template: "{{ state_attr('climate.tyr_celyn', 'current_temperature') }}"
        unit_of_measurement: °C
      tc_set_temperature:
        friendly_name: "Ty'r Celyn Set Temperature"
        value_template: "{{ state_attr('climate.tyr_celyn', 'temperature') }}"
        unit_of_measurement: °C
      tc_hvac_action:
        friendly_name: "Ty'r Celyn HVAC Action"
        value_template: "{{ state_attr('climate.tyr_celyn', 'hvac_action') }}"
        unit_of_measurement: none

timer:
  tyrcelyn_presence:
    name: TC - Presence Timer
    duration: '00:20:00'