homeassistant:
  customize:
    switch.living_room_fibaro_switch_switch:
      friendly_name: Main Light Switch
      icon: mdi:power-cycle
    switch.living_room_fibaro_switch_switch_2:
      friendly_name: Side Light Switch
      icon: mdi:power-cycle

binary_sensor:
  - platform: template
    sensors:
      zwave_living_room_fibaro_motion:
        device_class: motion
        friendly_name: Living Room Fibaro Motion
        value_template: "{{ is_state('binary_sensor.fgms001_zw5_motion_sensor_home_security_motion_detected', 'on') }}"
sensor:
  - platform: template
    sensors:
      zwave_living_room_fibaro_illuminance:
        value_template: "{{ '%.0f'%(states('sensor.fgms001_zw5_motion_sensor_illuminance') | float) }}"
        friendly_name: 'Living Room Fibaro Illuminance'
        unit_of_measurement: 'lux'
        device_class: illuminance

switch:
  - platform: template
    switches:
      zwave_living_room_main_light_switch:
        friendly_name: Main Light Switch
        value_template: "{{ is_state('switch.fibaro_double_switch_2_instance_1_switch', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.fibaro_double_switch_2_instance_1_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.fibaro_double_switch_2_instance_1_switch
      zwave_living_room_side_light_switch:
        friendly_name: Fireplace Light Switch
        value_template: "{{ is_state('switch.fibaro_double_switch_2_instance_2_switch', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.fibaro_double_switch_2_instance_2_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.fibaro_double_switch_2_instance_2_switch
