homeassistant:
  customize:
    switch.living_room_fibaro_switch_switch:
      friendly_name: Main Light Switch
      icon: mdi:power-cycle
    switch.living_room_fibaro_switch_switch_2:
      friendly_name: Side Light Switch
      icon: mdi:power-cycle
    sensor.motion_sensor_illuminance:
      unit_of_measurement: Lux

binary_sensor:
  - platform: template
    sensors:
      zwave_office_fibaro_motion:
        device_class: motion
        friendly_name: Office Fibaro Motion
        value_template: "{{ is_state('binary_sensor.motion_sensor_home_security_motion_detection', 'on') }}"
sensor:
  - platform: template
    sensors:
      zwave_office_fibaro_illuminance:
        value_template: "{{ '%.0f'%(states('sensor.motion_sensor_illuminance') | float(0)) }}"
        friendly_name: 'Office Fibaro Illuminance'
        unit_of_measurement: 'lux'
        device_class: illuminance
      zwave_office_fibaro_temperature:
        value_template: "{{ '%.0f'%(states('sensor.motion_sensor_air_temperature') | float(0)) }}"
        friendly_name: 'Office Fibaro Temperature'
        unit_of_measurement: '°C'
        device_class: temperature

switch:
  - platform: template
    switches:
      zwave_living_room_main_light_switch:
        friendly_name: Main Light Switch
        value_template: "{{ is_state('switch.double_switch_2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.double_switch_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.double_switch_2
      zwave_living_room_side_light_switch:
        friendly_name: Fireplace Light Switch
        value_template: "{{ is_state('switch.double_switch_2_2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.double_switch_2_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.double_switch_2_2
