frontend:
  themes: !include_dir_merge_named themes

automation:
camera:
climate:
config:
device_tracker:
diagnostics:
input_button:
mobile_app:
person:
# script: 
ssdp:
sun:
system_health:
system_log:
tts:
  - platform: google_translate
updater:
zeroconf:

